language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

#script:
#  - yarn test
#
#after_success:
#  - yarn coverage

before_deploy:
  - "yarn docz:build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs-dist
  on:
    branch: main
